import { useState } from "react";
import { useTranslation } from "react-i18next";
import { CircleNotch, DownloadSimple } from "@phosphor-icons/react";
import StorageFiles from "@/models/files";
import showToast from "@/utils/toast";

// File extension → display badge/colors. Lifted out of RunDetailPage with
// the file card itself; nothing else uses this map so it lives here.
// `typeKey` references the locale key for the human-readable file type so
// it can be translated at render time.
const FILE_DISPLAY_MAP = {
  pptx: {
    badge: "PPT",
    bg: "bg-orange-100",
    text: "text-orange-700",
    typeKey: "powerpoint",
  },
  ppt: {
    badge: "PPT",
    bg: "bg-orange-100",
    text: "text-orange-700",
    typeKey: "powerpoint",
  },
  pdf: {
    badge: "PDF",
    bg: "bg-red-100",
    text: "text-red-700",
    typeKey: "pdf",
  },
  doc: {
    badge: "DOC",
    bg: "bg-blue-100",
    text: "text-blue-700",
    typeKey: "word",
  },
  docx: {
    badge: "DOC",
    bg: "bg-blue-100",
    text: "text-blue-700",
    typeKey: "word",
  },
  xls: {
    badge: "XLS",
    bg: "bg-green-100",
    text: "text-green-700",
    typeKey: "spreadsheet",
  },
  xlsx: {
    badge: "XLS",
    bg: "bg-green-100",
    text: "text-green-700",
    typeKey: "spreadsheet",
  },
  csv: {
    badge: "CSV",
    bg: "bg-green-100",
    text: "text-green-700",
    typeKey: "spreadsheet",
  },
};

function getFileDisplayInfo(filename) {
  const extension = filename?.split(".")?.pop()?.toLowerCase() ?? "txt";
  return (
    FILE_DISPLAY_MAP[extension] || {
      badge: extension.toUpperCase().slice(0, 4),
      bg: "bg-slate-200",
      text: "text-slate-700",
      typeKey: "generic",
    }
  );
}

// Card representing a file generated by a job run. Streams the file from
// the storage API on download via dynamic import of file-saver.
export default function GeneratedFileCard({ file }) {
  const { t } = useTranslation();
  const [downloading, setDownloading] = useState(false);
  const { badge, bg, text, typeKey } = getFileDisplayInfo(file.filename);
  const typeLabels = {
    powerpoint: t("scheduledJobs.file.types.powerpoint"),
    pdf: t("scheduledJobs.file.types.pdf"),
    word: t("scheduledJobs.file.types.word"),
    spreadsheet: t("scheduledJobs.file.types.spreadsheet"),
    generic: t("scheduledJobs.file.types.generic"),
  };
  const type = typeLabels[typeKey];

  const handleDownload = async () => {
    if (downloading || !file.storageFilename) return;
    setDownloading(true);
    try {
      const blob = await StorageFiles.download(file.storageFilename);
      if (!blob) throw new Error("Failed to download file");
      const { saveAs } = await import("file-saver");
      saveAs(blob, file.filename || file.storageFilename);
    } catch {
      showToast(t("scheduledJobs.file.downloadFailed"), "error");
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="flex items-center justify-between border border-white/5 rounded-lg p-3 bg-theme-bg-primary/30">
      <div className="flex items-center gap-3 min-w-0">
        <div
          className={`${bg} ${text} rounded-lg flex items-center justify-center flex-shrink-0 h-10 w-10 text-xs font-bold`}
        >
          {badge}
        </div>
        <div className="flex flex-col min-w-0">
          <p className="text-sm font-medium text-theme-text-primary truncate">
            {file.filename || t("scheduledJobs.file.unknown")}
          </p>
          <p className="text-xs text-theme-text-secondary">
            {file.fileSize ? `${(file.fileSize / 1024).toFixed(1)} KB` : ""}
            {file.fileSize && type ? " · " : ""}
            {type}
          </p>
        </div>
      </div>
      <button
        type="button"
        onClick={handleDownload}
        disabled={downloading}
        className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-white/10 hover:bg-theme-bg-primary/70 transition-colors text-sm text-theme-text-primary flex-shrink-0 ml-4 disabled:opacity-50"
      >
        {downloading ? (
          <CircleNotch size={14} weight="bold" className="animate-spin" />
        ) : (
          <DownloadSimple size={14} weight="bold" />
        )}
        {downloading
          ? t("scheduledJobs.file.downloading")
          : t("scheduledJobs.file.download")}
      </button>
    </div>
  );
}
