# version: 2
# updates:
#   - package-ecosystem: "npm"
#     directory: "/frontend"
#     schedule:
#       interval: "weekly"
#   - package-ecosystem: "npm"
#     directory: "/server"
#     schedule:
#       interval: "weekly"
#   - package-ecosystem: "npm"
#     directory: "/collector"
#     schedule:
#       interval: "weekly"
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "weekly"
