version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: midhun
    ports:
      - "35432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  anything-llm-server:
    container_name: anything-llm-server
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    depends_on:
      - postgres
    volumes:
      - "./docker/.env:/app/server/config/.env"
      - "./server/storage:/app/server/storage"
      - "./server/:/app"
      - anything-llm-server-volume:/app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./docker/.env

volumes:
  anything-llm-server-volume:
