[Icon Theme]
Name=Fake10 Light
Comment=Faithful Windows 10 & 10-style icons
Inherits=hicolor
Directories=svg16,svg18,16,20,24,32,40,48,64,256

[svg16]
Size=16
Type=Scalable
MinSize=16
MaxSize=256

[svg18]
Size=18
Type=Scalable
MinSize=18
MaxSize=256

[16]
Size=16
Type=Fixed

[20]
Size=20
Type=Fixed

[24]
Size=24
Type=Fixed

[32]
Size=32
Type=Fixed

[40]
Size=40
Type=Fixed

[48]
Size=48
Type=Fixed

[64]
Size=64
Type=Fixed

[256]
Size=256
Type=Fixed