const MODELS = {
  "zero-one-ai/Yi-34B-Chat": {
    id: "zero-one-ai/Yi-34B-Chat",
    organization: "01.AI",
    name: "01-ai Yi Chat (34B)",
    maxLength: 4096,
  },
  "allenai/OLMo-7B-Instruct": {
    id: "allenai/OLMo-7B-Instruct",
    organization: "AllenAI",
    name: "OLMo Instruct (7B)",
    maxLength: 2048,
  },
  "Austism/chronos-hermes-13b": {
    id: "Austism/chronos-hermes-13b",
    organization: "Austism",
    name: "Chronos Hermes (13B)",
    maxLength: 2048,
  },
  "carson/ml318br": {
    id: "carson/ml318br",
    organization: "carson",
    name: "carson ml318br",
    maxLength: 8192,
  },
  "cognitivecomputations/dolphin-2.5-mixtral-8x7b": {
    id: "cognitivecomputations/dolphin-2.5-mixtral-8x7b",
    organization: "cognitivecomputations",
    name: "Dolphin 2.5 Mixtral 8x7b",
    maxLength: 32768,
  },
  "databricks/dbrx-instruct": {
    id: "databricks/dbrx-instruct",
    organization: "Databricks",
    name: "DBRX Instruct",
    maxLength: 32768,
  },
  "deepseek-ai/deepseek-llm-67b-chat": {
    id: "deepseek-ai/deepseek-llm-67b-chat",
    organization: "DeepSeek",
    name: "DeepSeek LLM Chat (67B)",
    maxLength: 4096,
  },
  "deepseek-ai/deepseek-coder-33b-instruct": {
    id: "deepseek-ai/deepseek-coder-33b-instruct",
    organization: "DeepSeek",
    name: "Deepseek Coder Instruct (33B)",
    maxLength: 16384,
  },
  "garage-bAInd/Platypus2-70B-instruct": {
    id: "garage-bAInd/Platypus2-70B-instruct",
    organization: "garage-bAInd",
    name: "Platypus2 Instruct (70B)",
    maxLength: 4096,
  },
  "google/gemma-2-9b-it": {
    id: "google/gemma-2-9b-it",
    organization: "google",
    name: "Gemma-2 Instruct (9B)",
    maxLength: 8192,
  },
  "google/gemma-2b-it": {
    id: "google/gemma-2b-it",
    organization: "Google",
    name: "Gemma Instruct (2B)",
    maxLength: 8192,
  },
  "google/gemma-2-27b-it": {
    id: "google/gemma-2-27b-it",
    organization: "Google",
    name: "Gemma-2 Instruct (27B)",
    maxLength: 8192,
  },
  "google/gemma-7b-it": {
    id: "google/gemma-7b-it",
    organization: "Google",
    name: "Gemma Instruct (7B)",
    maxLength: 8192,
  },
  "gradientai/Llama-3-70B-Instruct-Gradient-1048k": {
    id: "gradientai/Llama-3-70B-Instruct-Gradient-1048k",
    organization: "gradientai",
    name: "Llama-3 70B Instruct Gradient 1048K",
    maxLength: 1048576,
  },
  "Gryphe/MythoMax-L2-13b": {
    id: "Gryphe/MythoMax-L2-13b",
    organization: "Gryphe",
    name: "MythoMax-L2 (13B)",
    maxLength: 4096,
  },
  "Gryphe/MythoMax-L2-13b-Lite": {
    id: "Gryphe/MythoMax-L2-13b-Lite",
    organization: "Gryphe",
    name: "Gryphe MythoMax L2 Lite (13B)",
    maxLength: 4096,
  },
  "llava-hf/llava-v1.6-mistral-7b-hf": {
    id: "llava-hf/llava-v1.6-mistral-7b-hf",
    organization: "Haotian Liu",
    name: "LLaVa-Next (Mistral-7B)",
    maxLength: 4096,
  },
  "HuggingFaceH4/zephyr-7b-beta": {
    id: "HuggingFaceH4/zephyr-7b-beta",
    organization: "HuggingFace",
    name: "Zephyr-7B-ß",
    maxLength: 32768,
  },
  "togethercomputer/Koala-7B": {
    id: "togethercomputer/Koala-7B",
    organization: "LM Sys",
    name: "Koala (7B)",
    maxLength: 2048,
  },
  "lmsys/vicuna-7b-v1.3": {
    id: "lmsys/vicuna-7b-v1.3",
    organization: "LM Sys",
    name: "Vicuna v1.3 (7B)",
    maxLength: 2048,
  },
  "lmsys/vicuna-13b-v1.5-16k": {
    id: "lmsys/vicuna-13b-v1.5-16k",
    organization: "LM Sys",
    name: "Vicuna v1.5 16K (13B)",
    maxLength: 16384,
  },
  "lmsys/vicuna-13b-v1.5": {
    id: "lmsys/vicuna-13b-v1.5",
    organization: "LM Sys",
    name: "Vicuna v1.5 (13B)",
    maxLength: 4096,
  },
  "lmsys/vicuna-13b-v1.3": {
    id: "lmsys/vicuna-13b-v1.3",
    organization: "LM Sys",
    name: "Vicuna v1.3 (13B)",
    maxLength: 2048,
  },
  "togethercomputer/Koala-13B": {
    id: "togethercomputer/Koala-13B",
    organization: "LM Sys",
    name: "Koala (13B)",
    maxLength: 2048,
  },
  "lmsys/vicuna-7b-v1.5": {
    id: "lmsys/vicuna-7b-v1.5",
    organization: "LM Sys",
    name: "Vicuna v1.5 (7B)",
    maxLength: 4096,
  },
  "codellama/CodeLlama-34b-Instruct-hf": {
    id: "codellama/CodeLlama-34b-Instruct-hf",
    organization: "Meta",
    name: "Code Llama Instruct (34B)",
    maxLength: 16384,
  },
  "togethercomputer/Llama-3-8b-chat-hf-int4": {
    id: "togethercomputer/Llama-3-8b-chat-hf-int4",
    organization: "Meta",
    name: "Llama3 8B Chat HF INT4",
    maxLength: 8192,
  },
  "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo": {
    id: "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo",
    organization: "Meta",
    name: "Llama 3.2 90B Vision Instruct Turbo",
    maxLength: 131072,
  },
  "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo": {
    id: "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo",
    organization: "Meta",
    name: "Llama 3.2 11B Vision Instruct Turbo",
    maxLength: 131072,
  },
  "meta-llama/Llama-3.2-3B-Instruct-Turbo": {
    id: "meta-llama/Llama-3.2-3B-Instruct-Turbo",
    organization: "Meta",
    name: "Meta Llama 3.2 3B Instruct Turbo",
    maxLength: 131072,
  },
  "togethercomputer/Llama-3-8b-chat-hf-int8": {
    id: "togethercomputer/Llama-3-8b-chat-hf-int8",
    organization: "Meta",
    name: "Togethercomputer Llama3 8B Instruct Int8",
    maxLength: 8192,
  },
  "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo": {
    id: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
    organization: "Meta",
    name: "Meta Llama 3.1 70B Instruct Turbo",
    maxLength: 32768,
  },
  "meta-llama/Llama-2-13b-chat-hf": {
    id: "meta-llama/Llama-2-13b-chat-hf",
    organization: "Meta",
    name: "LLaMA-2 Chat (13B)",
    maxLength: 4096,
  },
  "meta-llama/Meta-Llama-3-70B-Instruct-Lite": {
    id: "meta-llama/Meta-Llama-3-70B-Instruct-Lite",
    organization: "Meta",
    name: "Meta Llama 3 70B Instruct Lite",
    maxLength: 8192,
  },
  "meta-llama/Llama-3-8b-chat-hf": {
    id: "meta-llama/Llama-3-8b-chat-hf",
    organization: "Meta",
    name: "Meta Llama 3 8B Instruct Reference",
    maxLength: 8192,
  },
  "meta-llama/Llama-3-70b-chat-hf": {
    id: "meta-llama/Llama-3-70b-chat-hf",
    organization: "Meta",
    name: "Meta Llama 3 70B Instruct Reference",
    maxLength: 8192,
  },
  "meta-llama/Meta-Llama-3-8B-Instruct-Turbo": {
    id: "meta-llama/Meta-Llama-3-8B-Instruct-Turbo",
    organization: "Meta",
    name: "Meta Llama 3 8B Instruct Turbo",
    maxLength: 8192,
  },
  "meta-llama/Meta-Llama-3-8B-Instruct-Lite": {
    id: "meta-llama/Meta-Llama-3-8B-Instruct-Lite",
    organization: "Meta",
    name: "Meta Llama 3 8B Instruct Lite",
    maxLength: 8192,
  },
  "meta-llama/Meta-Llama-3.1-405B-Instruct-Lite-Pro": {
    id: "meta-llama/Meta-Llama-3.1-405B-Instruct-Lite-Pro",
    organization: "Meta",
    name: "Meta Llama 3.1 405B Instruct Turbo",
    maxLength: 4096,
  },
  "meta-llama/Llama-2-7b-chat-hf": {
    id: "meta-llama/Llama-2-7b-chat-hf",
    organization: "Meta",
    name: "LLaMA-2 Chat (7B)",
    maxLength: 4096,
  },
  "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo": {
    id: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
    organization: "Meta",
    name: "Meta Llama 3.1 405B Instruct Turbo",
    maxLength: 130815,
  },
  "meta-llama/Llama-Vision-Free": {
    id: "meta-llama/Llama-Vision-Free",
    organization: "Meta",
    name: "(Free) Llama 3.2 11B Vision Instruct Turbo",
    maxLength: 131072,
  },
  "meta-llama/Meta-Llama-3-70B-Instruct-Turbo": {
    id: "meta-llama/Meta-Llama-3-70B-Instruct-Turbo",
    organization: "Meta",
    name: "Meta Llama 3 70B Instruct Turbo",
    maxLength: 8192,
  },
  "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo": {
    id: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
    organization: "Meta",
    name: "Meta Llama 3.1 8B Instruct Turbo",
    maxLength: 32768,
  },
  "togethercomputer/CodeLlama-7b-Instruct": {
    id: "togethercomputer/CodeLlama-7b-Instruct",
    organization: "Meta",
    name: "Code Llama Instruct (7B)",
    maxLength: 16384,
  },
  "togethercomputer/CodeLlama-34b-Instruct": {
    id: "togethercomputer/CodeLlama-34b-Instruct",
    organization: "Meta",
    name: "Code Llama Instruct (34B)",
    maxLength: 16384,
  },
  "codellama/CodeLlama-13b-Instruct-hf": {
    id: "codellama/CodeLlama-13b-Instruct-hf",
    organization: "Meta",
    name: "Code Llama Instruct (13B)",
    maxLength: 16384,
  },
  "togethercomputer/CodeLlama-13b-Instruct": {
    id: "togethercomputer/CodeLlama-13b-Instruct",
    organization: "Meta",
    name: "Code Llama Instruct (13B)",
    maxLength: 16384,
  },
  "togethercomputer/llama-2-13b-chat": {
    id: "togethercomputer/llama-2-13b-chat",
    organization: "Meta",
    name: "LLaMA-2 Chat (13B)",
    maxLength: 4096,
  },
  "togethercomputer/llama-2-7b-chat": {
    id: "togethercomputer/llama-2-7b-chat",
    organization: "Meta",
    name: "LLaMA-2 Chat (7B)",
    maxLength: 4096,
  },
  "meta-llama/Meta-Llama-3-8B-Instruct": {
    id: "meta-llama/Meta-Llama-3-8B-Instruct",
    organization: "Meta",
    name: "Meta Llama 3 8B Instruct",
    maxLength: 8192,
  },
  "meta-llama/Meta-Llama-3-70B-Instruct": {
    id: "meta-llama/Meta-Llama-3-70B-Instruct",
    organization: "Meta",
    name: "Meta Llama 3 70B Instruct",
    maxLength: 8192,
  },
  "codellama/CodeLlama-70b-Instruct-hf": {
    id: "codellama/CodeLlama-70b-Instruct-hf",
    organization: "Meta",
    name: "Code Llama Instruct (70B)",
    maxLength: 4096,
  },
  "togethercomputer/llama-2-70b-chat": {
    id: "togethercomputer/llama-2-70b-chat",
    organization: "Meta",
    name: "LLaMA-2 Chat (70B)",
    maxLength: 4096,
  },
  "codellama/CodeLlama-7b-Instruct-hf": {
    id: "codellama/CodeLlama-7b-Instruct-hf",
    organization: "Meta",
    name: "Code Llama Instruct (7B)",
    maxLength: 16384,
  },
  "meta-llama/Llama-2-70b-chat-hf": {
    id: "meta-llama/Llama-2-70b-chat-hf",
    organization: "Meta",
    name: "LLaMA-2 Chat (70B)",
    maxLength: 4096,
  },
  "meta-llama/Meta-Llama-3.1-8B-Instruct-Reference": {
    id: "meta-llama/Meta-Llama-3.1-8B-Instruct-Reference",
    organization: "Meta",
    name: "Meta Llama 3.1 8B Instruct",
    maxLength: 16384,
  },
  "albert/meta-llama-3-1-70b-instruct-turbo": {
    id: "albert/meta-llama-3-1-70b-instruct-turbo",
    organization: "Meta",
    name: "Meta Llama 3.1 70B Instruct Turbo",
    maxLength: 131072,
  },
  "meta-llama/Meta-Llama-3.1-70B-Instruct-Reference": {
    id: "meta-llama/Meta-Llama-3.1-70B-Instruct-Reference",
    organization: "Meta",
    name: "Meta Llama 3.1 70B Instruct",
    maxLength: 8192,
  },
  "microsoft/WizardLM-2-8x22B": {
    id: "microsoft/WizardLM-2-8x22B",
    organization: "microsoft",
    name: "WizardLM-2 (8x22B)",
    maxLength: 65536,
  },
  "mistralai/Mistral-7B-Instruct-v0.1": {
    id: "mistralai/Mistral-7B-Instruct-v0.1",
    organization: "mistralai",
    name: "Mistral (7B) Instruct",
    maxLength: 4096,
  },
  "mistralai/Mistral-7B-Instruct-v0.2": {
    id: "mistralai/Mistral-7B-Instruct-v0.2",
    organization: "mistralai",
    name: "Mistral (7B) Instruct v0.2",
    maxLength: 32768,
  },
  "mistralai/Mistral-7B-Instruct-v0.3": {
    id: "mistralai/Mistral-7B-Instruct-v0.3",
    organization: "mistralai",
    name: "Mistral (7B) Instruct v0.3",
    maxLength: 32768,
  },
  "mistralai/Mixtral-8x7B-Instruct-v0.1": {
    id: "mistralai/Mixtral-8x7B-Instruct-v0.1",
    organization: "mistralai",
    name: "Mixtral-8x7B Instruct v0.1",
    maxLength: 32768,
  },
  "mistralai/Mixtral-8x22B-Instruct-v0.1": {
    id: "mistralai/Mixtral-8x22B-Instruct-v0.1",
    organization: "mistralai",
    name: "Mixtral-8x22B Instruct v0.1",
    maxLength: 65536,
  },
  "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO": {
    id: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO",
    organization: "NousResearch",
    name: "Nous Hermes 2 - Mixtral 8x7B-DPO",
    maxLength: 32768,
  },
  "NousResearch/Nous-Hermes-Llama2-70b": {
    id: "NousResearch/Nous-Hermes-Llama2-70b",
    organization: "NousResearch",
    name: "Nous Hermes LLaMA-2 (70B)",
    maxLength: 4096,
  },
  "NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT": {
    id: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT",
    organization: "NousResearch",
    name: "Nous Hermes 2 - Mixtral 8x7B-SFT",
    maxLength: 32768,
  },
  "NousResearch/Nous-Hermes-Llama2-13b": {
    id: "NousResearch/Nous-Hermes-Llama2-13b",
    organization: "NousResearch",
    name: "Nous Hermes Llama-2 (13B)",
    maxLength: 4096,
  },
  "NousResearch/Nous-Hermes-2-Mistral-7B-DPO": {
    id: "NousResearch/Nous-Hermes-2-Mistral-7B-DPO",
    organization: "NousResearch",
    name: "Nous Hermes 2 - Mistral DPO (7B)",
    maxLength: 32768,
  },
  "NousResearch/Nous-Hermes-llama-2-7b": {
    id: "NousResearch/Nous-Hermes-llama-2-7b",
    organization: "NousResearch",
    name: "Nous Hermes LLaMA-2 (7B)",
    maxLength: 4096,
  },
  "NousResearch/Nous-Capybara-7B-V1p9": {
    id: "NousResearch/Nous-Capybara-7B-V1p9",
    organization: "NousResearch",
    name: "Nous Capybara v1.9 (7B)",
    maxLength: 8192,
  },
  "NousResearch/Hermes-2-Theta-Llama-3-70B": {
    id: "NousResearch/Hermes-2-Theta-Llama-3-70B",
    organization: "NousResearch",
    name: "Hermes 2 Theta Llama-3 70B",
    maxLength: 8192,
  },
  "openchat/openchat-3.5-1210": {
    id: "openchat/openchat-3.5-1210",
    organization: "OpenChat",
    name: "OpenChat 3.5",
    maxLength: 8192,
  },
  "Open-Orca/Mistral-7B-OpenOrca": {
    id: "Open-Orca/Mistral-7B-OpenOrca",
    organization: "OpenOrca",
    name: "OpenOrca Mistral (7B) 8K",
    maxLength: 8192,
  },
  "Qwen/Qwen2-72B-Instruct": {
    id: "Qwen/Qwen2-72B-Instruct",
    organization: "Qwen",
    name: "Qwen 2 Instruct (72B)",
    maxLength: 32768,
  },
  "Qwen/Qwen2.5-72B-Instruct-Turbo": {
    id: "Qwen/Qwen2.5-72B-Instruct-Turbo",
    organization: "Qwen",
    name: "Qwen2.5 72B Instruct Turbo",
    maxLength: 32768,
  },
  "Qwen/Qwen2.5-7B-Instruct-Turbo": {
    id: "Qwen/Qwen2.5-7B-Instruct-Turbo",
    organization: "Qwen",
    name: "Qwen2.5 7B Instruct Turbo",
    maxLength: 32768,
  },
  "Qwen/Qwen1.5-110B-Chat": {
    id: "Qwen/Qwen1.5-110B-Chat",
    organization: "Qwen",
    name: "Qwen 1.5 Chat (110B)",
    maxLength: 32768,
  },
  "Qwen/Qwen1.5-72B-Chat": {
    id: "Qwen/Qwen1.5-72B-Chat",
    organization: "Qwen",
    name: "Qwen 1.5 Chat (72B)",
    maxLength: 32768,
  },
  "Qwen/Qwen2-1.5B-Instruct": {
    id: "Qwen/Qwen2-1.5B-Instruct",
    organization: "Qwen",
    name: "Qwen 2 Instruct (1.5B)",
    maxLength: 32768,
  },
  "Qwen/Qwen2-7B-Instruct": {
    id: "Qwen/Qwen2-7B-Instruct",
    organization: "Qwen",
    name: "Qwen 2 Instruct (7B)",
    maxLength: 32768,
  },
  "Qwen/Qwen1.5-14B-Chat": {
    id: "Qwen/Qwen1.5-14B-Chat",
    organization: "Qwen",
    name: "Qwen 1.5 Chat (14B)",
    maxLength: 32768,
  },
  "Qwen/Qwen1.5-1.8B-Chat": {
    id: "Qwen/Qwen1.5-1.8B-Chat",
    organization: "Qwen",
    name: "Qwen 1.5 Chat (1.8B)",
    maxLength: 32768,
  },
  "Qwen/Qwen1.5-32B-Chat": {
    id: "Qwen/Qwen1.5-32B-Chat",
    organization: "Qwen",
    name: "Qwen 1.5 Chat (32B)",
    maxLength: 32768,
  },
  "Qwen/Qwen1.5-7B-Chat": {
    id: "Qwen/Qwen1.5-7B-Chat",
    organization: "Qwen",
    name: "Qwen 1.5 Chat (7B)",
    maxLength: 32768,
  },
  "Qwen/Qwen1.5-0.5B-Chat": {
    id: "Qwen/Qwen1.5-0.5B-Chat",
    organization: "Qwen",
    name: "Qwen 1.5 Chat (0.5B)",
    maxLength: 32768,
  },
  "Qwen/Qwen1.5-4B-Chat": {
    id: "Qwen/Qwen1.5-4B-Chat",
    organization: "Qwen",
    name: "Qwen 1.5 Chat (4B)",
    maxLength: 32768,
  },
  "snorkelai/Snorkel-Mistral-PairRM-DPO": {
    id: "snorkelai/Snorkel-Mistral-PairRM-DPO",
    organization: "Snorkel AI",
    name: "Snorkel Mistral PairRM DPO (7B)",
    maxLength: 32768,
  },
  "Snowflake/snowflake-arctic-instruct": {
    id: "Snowflake/snowflake-arctic-instruct",
    organization: "Snowflake",
    name: "Snowflake Arctic Instruct",
    maxLength: 4096,
  },
  "togethercomputer/alpaca-7b": {
    id: "togethercomputer/alpaca-7b",
    organization: "Stanford",
    name: "Alpaca (7B)",
    maxLength: 2048,
  },
  "teknium/OpenHermes-2-Mistral-7B": {
    id: "teknium/OpenHermes-2-Mistral-7B",
    organization: "teknium",
    name: "OpenHermes-2-Mistral (7B)",
    maxLength: 8192,
  },
  "teknium/OpenHermes-2p5-Mistral-7B": {
    id: "teknium/OpenHermes-2p5-Mistral-7B",
    organization: "teknium",
    name: "OpenHermes-2.5-Mistral (7B)",
    maxLength: 8192,
  },
  "test/test11": {
    id: "test/test11",
    organization: "test",
    name: "Test 11",
    maxLength: 4096,
  },
  "togethercomputer/guanaco-65b": {
    id: "togethercomputer/guanaco-65b",
    organization: "Tim Dettmers",
    name: "Guanaco (65B)",
    maxLength: 2048,
  },
  "togethercomputer/guanaco-13b": {
    id: "togethercomputer/guanaco-13b",
    organization: "Tim Dettmers",
    name: "Guanaco (13B)",
    maxLength: 2048,
  },
  "togethercomputer/guanaco-33b": {
    id: "togethercomputer/guanaco-33b",
    organization: "Tim Dettmers",
    name: "Guanaco (33B)",
    maxLength: 2048,
  },
  "togethercomputer/guanaco-7b": {
    id: "togethercomputer/guanaco-7b",
    organization: "Tim Dettmers",
    name: "Guanaco (7B)",
    maxLength: 2048,
  },
  "Undi95/ReMM-SLERP-L2-13B": {
    id: "Undi95/ReMM-SLERP-L2-13B",
    organization: "Undi95",
    name: "ReMM SLERP L2 (13B)",
    maxLength: 4096,
  },
  "Undi95/Toppy-M-7B": {
    id: "Undi95/Toppy-M-7B",
    organization: "Undi95",
    name: "Toppy M (7B)",
    maxLength: 4096,
  },
  "upstage/SOLAR-10.7B-Instruct-v1.0": {
    id: "upstage/SOLAR-10.7B-Instruct-v1.0",
    organization: "upstage",
    name: "Upstage SOLAR Instruct v1 (11B)",
    maxLength: 4096,
  },
  "togethercomputer/SOLAR-10.7B-Instruct-v1.0-int4": {
    id: "togethercomputer/SOLAR-10.7B-Instruct-v1.0-int4",
    organization: "upstage",
    name: "Upstage SOLAR Instruct v1 (11B)-Int4",
    maxLength: 4096,
  },
  "WizardLM/WizardLM-13B-V1.2": {
    id: "WizardLM/WizardLM-13B-V1.2",
    organization: "WizardLM",
    name: "WizardLM v1.2 (13B)",
    maxLength: 4096,
  },
};

module.exports.MODELS = MODELS;
