name: Test Docker Build

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'docker/**'
      - 'server/**'
      - 'frontend/**'
      - 'collector/**'
      - 'package.json'
      - '.github/workflows/docker-*.yml'

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract platform name
        id: platform
        run: echo "name=$(echo ${{ matrix.platform }} | sed 's/\//-/g')" >> $GITHUB_OUTPUT

      - name: Test build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          cache-from: type=gha,scope=${{ steps.platform.outputs.name }}
          cache-to: type=gha,mode=max,scope=${{ steps.platform.outputs.name }}
          build-args: |
            ARG_UID=1000
            ARG_GID=1000
