name: Test Dispatch

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Input was ${{ inputs.test_input }}"
